### PR TITLE
resources: add a lot of new relaxing sounds and remove old ones

### PR DESCRIPTION
**Pull request by pando85**

### CODE REVIEW

**Comment by tindleaj** [comment]
@pando85 Awesome. Do these sounds need any attribution? Also looks like this causes the container to overflow, so I'll need to add a scrollable element, but this is great. Where did you get the sounds?

**Comment by pando85** [comment]
From internet, really I dunno about attributions or licenses of the sounds :S sorry. I dunno if that matter either.

**Comment by tindleaj** [comment]
> From internet, really I dunno about attributions of licenses of the sounds :S sorry. I dunno if that matter either.

All good, ideally I'd like to track down any attributions/licenses of stuff in the repo, I can maybe do some reverse sound lookups to try and find them.

**Comment by pando85** [comment]
Go a head :), in the future could be cool to have our own recordings. I have a friend with a good stereo microphone.

**Comment by pando85** [comment]
Added scrollbar. Credits by @OmarSanchezC.

**Pull request merged**
